// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-release.fsx"
#load "../ProjectSystem/OpenDocumentsTracker.fs"
      "../ProjectSystem/ProjectConfig.fs"
      "../ProjectSystem/ProjectSitesAndFiles.fs"
      "../ProjectSystem/HostServices.fs"
      "../ProjectSystem/FSharpWorkspace.fs"
      "../ProjectSystem/FileSystem.fs"
      "../ProjectSystem/LanguageService.fs"
      "../ProjectSystem/SolutionProvider.fs"
      "../ProjectSystem/FileSystemWatcher.fs"
      "../ProjectSystem/SolutionFileInfo.fs"
      "../Navigation/NavigableItemsCollector.fs"
      "../Navigation/NavigateToIndex.fs"
      "../Navigation/NavigableItemCache.fs"
      "../Navigation/NavigateToItem.fs"
      "../Navigation/GoToDefinition.fs"
      "../Navigation/GoToSignature.fs"
      "../Navigation/GoToImplementation.fs"
      "../Navigation/GoToDeclaration.fs"
      "../Navigation/NavigateToReferenceSource.fs"
      "../Navigation/NavigateToMetadata.fs"
      "../Documentation/XmlDocParser.fs"
      "../Documentation/XmlDocBuilder.fs"
      "../Documentation/XmlDocGenerator.fs"
      "../Documentation/XmlDocCache.fs"
      "../Coloring/DepthParser.fs"
      "../Coloring/OpenDeclarationsGetter.fs"
      "../Coloring/UnopenedNamespacesResolver.fs"
      "../Coloring/HighlightUsageInFile.fs"
      "../Coloring/PrintfSpecifiersUsageGetter.fs"
      "../Coloring/DocumentHighlights.fs"
      "../Symbols/SymbolHelpers.fs"
      "../Symbols/SourceCodeClassifier.fs"
      "../Symbols/QuickInfoProvider.fs"
      "../CodeGeneration/IndentedTextWriter.fs"
      "../CodeGeneration/CodeGeneration.fs"
      "../CodeGeneration/SignatureGenerator.fs"
      "../CodeGeneration/UnionPatternMatchCaseGenerator.fs"
      "../CodeGeneration/InterfaceStubGenerator.fs"
      "../CodeGeneration/RecordStubGenerator.fs"
      "../Structure/BlockStructure.fs"
      "../Completion/SignatureHelp.fs"
      "../Completion/FileSystemCompletion.fs"
