// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Editing.Messages")>]
[<assembly: AssemblyProductAttribute("FSharp.Editing")>]
[<assembly: AssemblyDescriptionAttribute("Rich F# language support for editors")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Editing.Messages"
    let [<Literal>] AssemblyProduct = "FSharp.Editing"
    let [<Literal>] AssemblyDescription = "Rich F# language support for editors"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
